// Generated by CoffeeScript 1.10.0
var ControlContainer;

ControlContainer = React.createClass({displayName: "ControlContainer",
  render: function() {
    return React.createElement(Nav, {
      "bsStyle": 'pills'
    }, React.createElement(NavItem, {
      "title": "Channel"
    }, "Channel"));
  }
});
